pipeline {
    agent {
        node {
            label 'AGENT-1'
        }
    }
    options {
        timeout(time: 1, unit : 'HOURS')
        disableConcurrentBuilds()
        
    }
    stages{
    stage('Init') {
            steps {
                sh """
                  cd 01-vpc
                  terraform init
                """
            }
        }
    stage('Plan') {
            steps {
                sh """
                  cd 01-vpc
                  terraform plan
                """
            }
        }

    input {
            message "Should we continue?"
            ok "Yes, we should."
        }

    stage('Apply') {
            steps {
                sh """
                  cd 01-vpc
                  terraform apply -auto-approve
                """
            }
        }
    }
    post { 
        always { 
            echo 'I will always say Hello again Narasimha!'
        }
        failure { 
            echo 'Pipeline failed!'
        }
        success { 
            echo 'I will always say when success'
        } 
    }
 }
